#-------系统默认配置----------
spring:
#数据库配置,(url,username,password)必填
  datasource:
    url: jdbc:mysql://localhost:3306/hcrm-ireport?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

security:
  basic:
    enabled: false

#mybatis配置
mybatis:
    type-aliases-package: com.kyee.model
    mapper-locations: classpath:com/kyee/mapper/*.xml

mapper:
    mappers:
        - com.kyee.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#日志
logging:
  path: /Users/zrc/Downloads/DB/
server:
  port: 8070